### ISSUE TITLE
V3 focus style slightly overlaps text where line height and spacing are low

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#1028]
Some components have links closely spaced or links that can wrap onto a second line. With the new V3 focus styles this can cause some minor text cropping/overlapping issues, specifically:

Text beneath focussed link is too close:

<img width="796" alt="Screen Shot 2019-08-07 at 11 06 00" src="https://user-images.githubusercontent.com/861310/62681164-f35f4300-b9b0-11e9-8d6b-7f141527d432.png">

Text wrapped onto a second line causes the lower part of some letters in the first line to be cut off:

<img width="583" alt="Screen Shot 2019-08-06 at 13 21 54" src="https://user-images.githubusercontent.com/861310/62681188-0114c880-b9b1-11e9-8257-e57fc8a7c893.png">

Components to fix:

- [x] image card
- [x] attachment
- [x] textarea
- [x] metadata
- [x] organisation logo
- [x] related navigation
- [x] [document list](https://github.com/alphagov/finder-frontend/pull/1307#issuecomment-521974898)
- [ ] possibly others?

This issue should be addressed after [the V3 PR](https://github.com/alphagov/govuk_publishing_components/pull/1010) has been merged.

**Comment by injms** [comment]
I'll take a look at this, since it's blocking a release on government-frontend.

**Comment by andysellick** [comment]
Interestingly this issue is noticeable on the Design System website.
