### ISSUE TITLE
Layout header links can overlap title/logo

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#1029]
Before links collapse into a menu on mobile, if the text is too long it can overlap the main header title.

<img width="784" alt="Screen Shot 2019-08-07 at 13 14 28" src="https://user-images.githubusercontent.com/861310/62681533-d24b2200-b9b1-11e9-8f08-e37352fe0fdc.png">

(also why are these two links different colours?)

Potentially related - when the links do collapse into a menu on mobile, the dropdown doesn't appear to work in the component guide. Worth investigating.

**Comment by alex-ju** [comment]
This bug is currently in production in [`content-publisher`](https://github.com/alphagov/content-publisher) and it's caused when the environment tag was introduced. Needs additional code on top of the styles coming from `govuk-frontend`, as this environment tag is a feature specific to how the component is implemented in `govuk_publishing_components`.

**Comment by injms** [comment]
The bug also extends to another clash at 320px screen width:

![image](https://user-images.githubusercontent.com/1732331/63284056-ab8ec480-c2aa-11e9-828b-d7b1074c0274.png)

**Comment by alex-ju** [comment]
Is this good to be closed after #1057?

**Comment by injms** [comment]
> Is this good to be closed after #1057?

#1057 fixes the overlap on desktop, but doesn't fix overlap on smaller screens.

**Comment by kr8n3r** [comment]
this is caused by 
```
.gem-c-header__logo {
    white-space: nowrap;
}
```
design system doesn't have that, so need to figure out why it exists here

**Comment by nickcolley** [comment]
I wonder if the no wrapping was added to get around this upstream bug: https://github.com/alphagov/govuk-frontend/issues/1502 ?

**Comment by kr8n3r** [comment]
@nickcolley possibly, but we don't seem to have that issue in here
