### ISSUE TITLE
Table component column sort isn't working?

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#1031]
The sort option for the table component seems to be non-functional in the component guide - clicking the column headers takes the browser to `/`. Might be limited to the component guide but worth investigation.

<img width="801" alt="Screen Shot 2019-08-07 at 16 52 41" src="https://user-images.githubusercontent.com/861310/62681976-e5122680-b9b2-11e9-8f08-49c202dd85c7.png">

**Comment by alex-ju** [comment]
The sorting is meant to be done on the server side, not the client side. Documentation should be updated to reflect that.
