### ISSUE TITLE
Step by step focus with hover has wrong text colour

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#1058]
I think by re-ordering the CSS this could resolve this issue.

This is an issue for the 'show all' link button too.

<img width="282" alt="" src="https://user-images.githubusercontent.com/2445413/63341855-0fb09780-c342-11e9-992e-a64635c29726.png">
<img width="141" alt="" src="https://user-images.githubusercontent.com/2445413/63341865-150de200-c342-11e9-95a4-84002505161b.png">

**Comment by alex-ju** [comment]
@nickcolley the show all link has already been addressed #1119 is going to fix the case when the button is focused and its parent div is hovered (it has a twisted structure indeed).

**Comment by nickcolley** [comment]
Nice work, thanks Alex :+1:
