### ISSUE TITLE
Text highlight in 'form input with icon' offset

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/govuk_publishing_components#1180]
See GIF
![lazy-highlight](https://user-images.githubusercontent.com/3758555/67564584-2a750300-f71b-11e9-957b-96f5f9d93c3d.gif)

the "lag" is the width of the padding/space set aside for the icon

Recording it, but don't think users have complained.

**Comment by danacotoran** [comment]
As far as I can tell the search box doesn't look like this anymore, therefore this issue should no longer exist. 
Therefore I'll take the liberty of closing this issue (but do feel free to reopen it if I'm wrong).
