### ISSUE TITLE
Feedback component button/link alignment

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/govuk_publishing_components#1217]
"Page not useful" form button / link alignement is not the best on certain widths

<img width="602" alt="Screenshot 2019-12-06 at 09 38 19" src="https://user-images.githubusercontent.com/3758555/70312901-6d42f400-180c-11ea-8d1a-90e18302cb83.png">
<img width="643" alt="Screenshot 2019-12-06 at 09 38 33" src="https://user-images.githubusercontent.com/3758555/70312902-6d42f400-180c-11ea-9e88-f08aad7dad63.png">
<img width="530" alt="Screenshot 2019-12-06 at 09 38 41" src="https://user-images.githubusercontent.com/3758555/70312903-6ddb8a80-180c-11ea-8a3f-3e11f20a2cd4.png">

**Comment by kr8n3r** [comment]
it would be really beneficial to be able to add a class to the button component and add a 15px right margin.
below is with display:inline-flex on the link
![flex](https://user-images.githubusercontent.com/3758555/70315943-86e73a00-1812-11ea-94f8-06c79c64cd84.gif)

**Comment by andysellick** [comment]
Maybe just drop the link onto the line below regardless?

**Comment by kr8n3r** [comment]
yeah i could make the breakpoint shift to desktop widths where there definitely is enough space for them to be side-by-side. 
would be nice to use that space beforehand though.
