### ISSUE TITLE
Update SCSS linting to be stricter

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#124]
This should align with GOV.UK Frontend project if possible.

https://github.com/alphagov/govuk_publishing_components/pull/116/files/6e58bf10b1586388a22c76d47e82d939600d0889..f5da3377ca30ddab628e72ae7d7b61876f5cbbbf#r159670908

**Comment by fofr** [comment]
Should be linting by default:
https://github.com/alphagov/govuk_publishing_components/blob/master/Jenkinsfile

🤔

**Comment by nickcolley** [comment]
Maybe the linting doesnt care about new lines and we could make it stricter?

**Comment by alex-ju** [comment]
@nickcolley this repo is now using the same [.sass-lint](https://github.com/alphagov/govuk_publishing_components/blob/master/.sass-lint.yml) rules with GOV.UK Frontend. Are you fine with me to close this?

**Comment by nickcolley** [comment]
Sure thing
