### ISSUE TITLE
YoutubeLinkEnhancement doesn't kick in until second page view

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk_publishing_components#1256]
## Background

The YouTube link enhancement govspeak script looks for links to YouTube and progressively enhances the link into an inline embedded video.

Our cookie implementation wraps this script in a conditional, so that the links are **not** enhanced unless the user has explicitly clicked "Accept all cookies". (This is for compliance reasons, as YouTube embeds would set cookies on the user machine.)

Here is an example page with a YouTube link: https://www.gov.uk/guidance/hmcts-video-hearings-guidance-for-legal-professionals

## Expected behaviour

When visiting a page with a YouTube link, if I click 'accept all cookies', the link should immediately be enhanced into an inline embedded video.

## Actual behaviour

The YouTube link is not swapped out for a video, even after accepting cookies. I have to refresh the page in order to trigger the progressive enhancement.

## Consequences

Users who are new to GOV.UK, or who are visiting a GOV.UK page using a browser they haven't used for it before (e.g. Facebook browser), will not see any videos on the page. This could cause confusion.

## Possible solution

The reason we have this bug is as follows: we evaluate whether or not the user has accepted the cookies, before they've had the time to accept the cookies.

We could consider some sort of publish/subscribe pattern whereby clicking ‘accept’ triggers an event that enhancement code can hook into, so that we can enhance links into videos as soon as the ‘accept’ button is pressed. This would be extensible, in that you could publish changes to consent from both the cookie banner and cookie settings page.

Or we could use a custom element in place of the link, rendered on the server. It would be responsible for figuring out if cookies have been accepted.

**Comment by nickcolley** [comment]
Idea:

Only enhance YouTube links when they enter the viewport using Intersection Observers.

Con: any links above the fold might run into the same issues described here.

**Comment by andysellick** [comment]
I don't know how the YouTube code works, but could we wrap it in something that checks for cookie consent, if no consent then it wraps it in something that informs the user and allows them to click to accept cookies, thereby initialising both the video and cookies (in a similar way to how the current pageview is fired by calling the analytics code init when users click 'yes' on the cookie banner)?

Sorry, that was a very long sentence.

**Comment by nickcolley** [comment]
Maybe related to what Andy is suggesting:

https://do-not-track-third-party-embeds.glitch.me/
