### ISSUE TITLE
Hiding checkbox heading does not work

### ISSUE THREAD

**Issue by faissalMT** [alphagov/govuk_publishing_components#1284]
We're trying to start using govuk_publishing_components 21.22.1 over on https://github.com/DFE-Digital/find-teacher-training and would like to use the following feature:
https://components.publishing.service.gov.uk/component-guide/checkboxes/with_a_hidden_heading  
However copying this example verbatim does not work.

**Comment by injms** [comment]
Hi @faissalMT 

Sorry to hear it's not working. Do you have any more information about what's not working or error messages that you could share to help us dig into the problem?

Cheers,

Ian

**Comment by faissalMT** [comment]
There are no error messages, the flag simply doesn't change anything. The heading displays as it would without the flag.

**Comment by injms** [comment]
Hmm, without any example code or error messages it's tricky to know how to fix this. It could be anything, so it's hard to offer help without knowing specifics. It'd help if you could share the exact code that's not working - just to check that it is verbatim - and the style cascade that's affecting the `<legend>` that should be hidden.

**Comment by faissalMT** [comment]
I'm closing this issue because we've switched to another approach.
