### ISSUE TITLE
The use of 'dummy' app is not documented

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk_publishing_components#1355]
We use the 'dummy' app in our testing suite, for visually testing helpers, layouts and potentially other things, but we have no documentation around it and there is a lack of knowledge around it at the community level.

**Comment by andysellick** [comment]
When the guide is shown in an application (e.g. finder-frontend) the stylesheet from that application is pulled into the guide. When the guide is run in standalone mode, the stylesheet from the dummy app is pulled in instead. I don't know why - it's possible the code is built in such a way that it requires an app to function. @nickcolley will know more.

**Comment by nickcolley** [comment]
the dummy app is so this gem can be tested in the way it'd be run when added to an app, I believe we copied the convention for this from other similar gems, I dont know anymore than that sorry

**Comment by alex-ju** [comment]
Thanks @nickcolley, I think we can figure the specifics out from code, raised this to remind ourselves to carry on this bit of investigation and add documentation around it.

**Comment by andysellick** [comment]
My previous comment is now out of date - we've now removed the application (and dummy application) stylesheet from the component guide, for reasons documented in this PR: https://github.com/alphagov/govuk_publishing_components/pull/1409

**Comment by alex-ju** [comment]
The dummy app is now lightly documented in #2664
