### ISSUE TITLE
jQuery is out of date

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#1374]
[Dependabot just reminded us](https://github.com/alphagov/govuk_publishing_components/pull/1371) that we're using quite an old version of jQuery. I believe that's because the current version (>3) doesn't support older browsers that we might still be supporting.

I think the intention is to remove our dependency on jQuery and therefore remove this problem, but it might be worth raising the issue so we give it a little more attention.

**Comment by injms** [comment]
[jQuery's page on supported browsers](https://jquery.com/browser-support/) says that the current version (3.4.1) support Internet Explorer 9 onwards. Internet Explorer 6-8, Opera 12.1x or Safari 5.1+, need to use use jQuery 1.12.

**Comment by nickcolley** [comment]
> Avoid jQuery in new projects.
>
> In older projects put together a plan to migrate away from jQuery.
>
>**Why:** jQuery had been used to provide browser support for older browsers. However, browser support for ES5 JavaScript is now widespread enough that a library like jQuery is unnecessary. The older versions of jQuery that we use have security vulnerabilities and are no longer maintained by the jQuery team.

https://gds-way.cloudapps.digital/manuals/programming-languages/js.html#jquery

**Comment by andysellick** [comment]
jQuery has now been removed from GOV.UK.
