### ISSUE TITLE
Remove hosted component styles from component guide stylesheet

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_publishing_components#139]
Applications that want to use components from this gem need to include the styles. When included they'll be made available to the app's component guide.

By including them in the component guide automatically we are giving a false impression that they'll work as intended in the app. As we use component guides to review PRs this feels like a false positive that could lead to broken deploys.

We should remove hosted component styles from the component guide stylesheet.

We include them here:
https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/application.scss#L7-L13

Example problem here:
https://github.com/alphagov/government-frontend/pull/672

**Comment by nickcolley** [comment]
This makes sense to me.
