### ISSUE TITLE
Unable to add `spellcheck` attribute to input component

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#1391]
Setting `spellcheck` to `false` is useful for form fields the don't need spellchecking - such as ID numbers, email address, name and so on. 

Need shown in discussion on vulnerable people coronavirus form: https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form/pull/88

Maybe like this?

```erb
<%= render "govuk_publishing_components/components/input", {
  label: {
    text: "What is your name?"
  },
  name: "name",
  spellcheck: false,
} %>
```

**Comment by owenatgov** [comment]
Is there still a use case for this? On one hand it's good practice but on the other I wonder if this will actually get used anywhere.

**Comment by injms** [comment]
I'd say it's still relevant and useful but not urgent.

It's sort of been usurped by https://github.com/alphagov/govuk_publishing_components/issues/2488 - if that method gets used, this issue is irrelevant as the attribute could be added without updating the component.

**Comment by andysellick** [comment]
Closing in favour of https://github.com/alphagov/govuk_publishing_components/issues/2488
