### ISSUE TITLE
Component CSS included twice

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#144]
For components in the gem, it looks like their CSS is being included twice.

![screen shot 2018-01-19 at 12 21 32](https://user-images.githubusercontent.com/861310/35150726-64dae5a4-fd13-11e7-9399-e180084f0f50.png)

Weirdly this only seems to happen for gem components, and only in the government-frontend component guide (not static) - limited to apps?

**Comment by tijmenb** [comment]
Is this the same issue as https://github.com/alphagov/govuk_publishing_components/issues/139?

**Comment by fofr** [comment]
@tijmenb Yes

**Comment by tijmenb** [comment]
👍 closing this one then.
