### ISSUE TITLE
Port SmartAnswers checkbox "none" enhancement

### ISSUE THREAD

**Issue by chao-xian** [alphagov/govuk_publishing_components#1456]
Smart Answers in the only frontend app that deselects checkboxes that are not labelled "none":

https://github.com/alphagov/smart-answers/blob/master/app/assets/javascripts/helpers.js#L29

See https://smart-answers-preview.herokuapp.com/business-coronavirus-support-finder/y/england/0_to_249/85k_to_45m/yes/no/51k_and_over

**Comment by alex-ju** [comment]
@chao-xian we added this to the CV19 service's backlog and we hope to work on it soon
