### ISSUE TITLE
Components audit doesn't work on the main components website

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk_publishing_components#1661]
Visiting https://components.publishing.service.gov.uk/component-guide/audit show 'application not found' for every app.

<img width="1439" alt="Screenshot 2020-08-25 at 12 07 13" src="https://user-images.githubusercontent.com/788096/91167441-e00e3b00-e6cb-11ea-9f69-a77af1c845b6.png">

**Comment by andysellick** [comment]
I knew about this, but it's good to record it. Unfortunately the way the audits page works we can't get the data for the applications in here. Some of the stuff in the 'components' tab should still work, but maybe we can make this page better.

I could probably add a flag to say if all of the applications aren't found, replace the content of the 'applications' tab with a better error message.
