### ISSUE TITLE
Share links & brand guidelines

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#1724]
It seems use of 3rd party logos within [Share Links ](https://components.publishing.service.gov.uk/component-guide/share_links)  doesn't comply with their [respective brand guidelines](https://en.facebookbrand.com/facebookapp/assets/f-logo/), this could be worth revisiting.   An example is the 'f' logo:

![Screenshot-2020-10-08-at-14 24 14](https://user-images.githubusercontent.com/71266765/95465055-95423d00-0972-11eb-9f9a-c2163ee0c9c6.jpg)

**Comment by alex-ju** [comment]
Thank you for flagging this up, Chris! I don't have the full context on how these were built, but I sense there wasn't a 3rd party design used, but rather Facebook changing their logo and guidelines over time. It can be seen as design debt, which why I tagged it accordingly, but I suspect this might not be a priority for our designers for now as it's not driven by a user need.
