### ISSUE TITLE
Step icons clipped on IE11

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#1801]
## What? 

As part of PR [1799](https://github.com/alphagov/govuk_publishing_components/pull/1799) the "step icons" as part of _govspeak_ are slightly clipped on IE11 and might be worth enhancing / improving at a later date.

![image](https://user-images.githubusercontent.com/71266765/100773964-79e73180-33f9-11eb-8d91-7da45c4fd9cc.png)

## Why?

Changing the SVG to resolve a different issue introduced this less than ideal IE11 visual.

**Comment by MartinJJones** [comment]
Issue resolved as part of this PR - https://github.com/alphagov/govuk_publishing_components/pull/3166

IE11 - Browserstack

<img width="881" alt="Screenshot 2023-07-28 at 11 50 29" src="https://github.com/alphagov/govuk_publishing_components/assets/28779939/1f279d3a-e3f3-4236-be8a-ce29b17c724a">
