### ISSUE TITLE
Dynamic filtered search vs click search

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#1834]
## What?

As part of [this PR](https://github.com/alphagov/collections/pull/2148/) a [search input field on this page](https://www.gov.uk/government/organisations) was swapped to use the [Search Gem](https://components.publishing.service.gov.uk/component-guide/search)

However what was noticed was that the Search Button becomes redundant when used in a dynamic filtering context. The user just needs to type, they don't need to click search.

 ## Visuals 
You can see this issue demoed below, as the user searches the actual search button is not used. [Other use cases can be found here](https://www.gov.uk/search/all?keywords=test&order=relevance) where the filtering is happening on blur, again the button is not necessarily used.

![ezgif-7-4b9b93c0048b](https://user-images.githubusercontent.com/71266765/102383482-8061d580-3fc3-11eb-9ea2-7ce5642a200a.gif)

## Possible solutions

Create a variant within the Search gem so that when on key-down filtering is being used for search, the button is changed to an icon and this is swapped to a clear icon when typing.

[I note the Design System's reference to search](https://github.com/alphagov/govuk-design-system-backlog/issues/132)

**Comment by chris-gds** [comment]
Considerations: 
https://github.com/alphagov/tech-docs-gem/issues/262

**Comment by jon-kirwan** [comment]
It looks like the solution, e.g. on the organisations page https://www.gov.uk/government/organisations, has been to use the input component, when a search icon isn't needed. It seems like an unnecessary enhancement, and recent DAC audits haven't raised any concerns regarding its usage.
