### ISSUE TITLE
Add tracking to list component 

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#1887]
## What?

Add general `data-` / tracking options to the [list component.](https://components.publishing.service.gov.uk/component-guide/list)

## Why?

As part of work actioned [on this PR](https://github.com/alphagov/collections/pull/2231) a list that appears [on this page](https://www.gov.uk/coronavirus) was converted to use the list component to align with the Design System, gem and improve a11y.  However tracking is not something this component supports at present.

Consider:

`<%= render "govuk_publishing_components/components/list", {
  items: [
    sanitize("<a href=\"#{item["url"]}\" rel=\"noopener\" class=\"govuk-link covid__accordion-link\" >#{item["url"]}</a>"),
    ]
} %>`

vs

`<%= link_to(
  item["label"],
  item["url"],
  class: "govuk-link covid__accordion-link",
  data: {
    track_category: "pageElementInteraction",
    track_action: "AccordionClick",
    track_label: item["url"],
    }
  ) %>`

**Comment by andysellick** [comment]
Closing for now as the analytics is currently under review and may change soon.
