### ISSUE TITLE
Cookies banner previews are broken with javascript disabled

### ISSUE THREAD

**Issue by maxgds** [alphagov/govuk_publishing_components#1932]
The Cookies Banner component is written so that if the user doesn't have js switched on/working they should see the component persist with links through to the settings page. This works in production but fails on the documentation page for reasons currently unknown - instead of seeing the banner the previews show up as blank alongside the example implementation code.

**Comment by alex-ju** [comment]
I think we only need to [remove these lines](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/component_guide/application.scss#L265-L271) for it to work.
