### ISSUE TITLE
Structure of accordion and accordion docs content needs tidying up

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk_publishing_components#1941]
This issue encompasses 2 problems uncovered in https://github.com/alphagov/govuk_publishing_components/pull/1937

1. There is content in the accordion js, specifically the grammatical screen reader additions for the show/hide buttons, which is isolated to that js. It could be added to a translation file and instead passed to the component in the markup, reducing the risk of the wrong language being shown to users. This is also true for the step by step component.
2. Throughout the docs for the accordion, there are several single lines of content surrounded by quotes. This isn't necessary in YML.

**Comment by andysellick** [comment]
The step by step component should already be getting its text from data attributes in the template, from the translation file - unless it's changed recently.

**Comment by owenatgov** [comment]
The "this section" stuff isn't, that was added hastily during the run-up to WCAG-geddon last September.

**Comment by owenatgov** [comment]
This has now been solved by the linked PR
