### ISSUE TITLE
JS bug on pages that use the govspeak magna charta stacked chart

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk_publishing_components#1968]
On pages using the magna charta stacked variant, there is a js error triggered by the stacked chart specifically. This is causing any js that has yet to be run after the offending chart to break, including the feedback component.

[Examples page](https://www.gov.uk/government/publications/government-digital-inclusion-strategy/government-digital-inclusion-strategy)

**Comment by andysellick** [comment]
Error seems to occur here: https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js#L264

![Screenshot 2022-03-14 at 16 18 48](https://user-images.githubusercontent.com/861310/158215399-48f0494c-07c4-405c-afae-91ca57a7d9ca.png)
