### ISSUE TITLE
Print button interaction 

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#1970]
## What?

It was [highlighted on this page](https://www.gov.uk/government/publications/government-digital-inclusion-strategy/government-digital-inclusion-strategy) that as a user scrolls the [Print button ](https://components.publishing.service.gov.uk/component-guide/print_link)does not switch between being fixed and relative in the visual manner as expected.

https://user-images.githubusercontent.com/71266765/110766455-16b53880-824d-11eb-85cd-f213e4e9e452.mov

**Comment by alex-ju** [comment]
This is a duplicate of https://github.com/alphagov/government-frontend/issues/1907

**Comment by DilwoarH** [comment]
I'll leave a comment on #1907 - thanks for raising it to my attention again @chris-gds

**Comment by alex-ju** [comment]
The instance you mentioned, Chris, might actually be caused by the failing `magna-charta` script.

**Comment by andysellick** [comment]
Fixed by @DilwoarH
