### ISSUE TITLE
Make sure that success alert component is using the correct link styles

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk_publishing_components#2008]
The new [success alert component](https://components.publishing.service.gov.uk/component-guide/success_alert), which is inherited from the [success variant of the design system notification banner](https://design-system.service.gov.uk/components/notification-banner), uses an explicit class to style it's links to be green (`govuk-notification-banner__link`).

Some comments from the design system team on the link colour choice:

>I believe it was a design/consistency thing, so the link looked consistent within its container. It's also similar to what we do for the error summary component.

>Yeah it’s to make each kind of banner look like its own distinct thing, and have a more cohesive appearance. It looks a bit wrong, even broken, when the links are a different colour to the banner! I’d worry about GOV.UK veering from the standard component on something like this just cos service teams might copy it

[Further reading on the implementation choice](https://github.com/alphagov/govuk-frontend/issues/1934)

This can't be implemented at the component level as we don't have total control over what content will be coming in, so we need to go through the [instances of the success alert across govuk apps](https://github.com/search?q=org%3Aalphagov+components%2Fcomponents%2Fsuccess_alert&type=Code) and make sure that any instances of links within the success alert component are using the above class.

Additionally, guidance should be added to the component docs advising to use the link class if you success alert content includes a link.

**Comment by chris-gds** [comment]
🤔   Would _something_ like this work? I'm trying to think, ideally you want to inherit, apply to all, but also scope
```
.gem-c-success-alert {
  a {
    @extend .govuk-notification-banner__link;
  }
}
```

**Comment by owenatgov** [comment]
@chris-gds This could work yes, but if the DS team ever change this component then this would be a divergence might get missed. The DS team have made an informed decision about this and I'd rather lean on their implementation than try roll our own. Check out the convo in the DS issue I linked to for some more detailed whys.

**Comment by owenatgov** [comment]
I've had a nosey through the uses of success alert and haven't found any that use links in their body besides the cookie banner. I'm going to make a PR with some extra guidance on the success alert in a bit.

**Comment by owenatgov** [comment]
Marking as resolved for now. It doesn't look like there's a great need to use links in success alert components across govuk at present. I may bring this up in a future frontenders catchup to gauge thoughts on this.
