### ISSUE TITLE
`window.GOVUK.VisualDiffTool()` broken - CSP policy blocks iframe and preview URLs incorrect

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2014]
The `window.GOVUK.VisualDiffTool()` is a quick visual regression test where it:

1. loads the live version of a component preview in an iframe
2. places the iframe over the current page
3. make the new iframe semi-transparent and uses CSS's mix-blend-mode to show the difference between the two pages

This is currently broken because:
 - the content security policy blocks Heroku previews from loading in an iframe
 - the preview URLs are incorrect - for example, `frontend.herokuapp.com` isn't a GOV.UK Publishing app

## Steps to replicate

1. Run a frontend application locally so that you can visit it using `*.dev.gov.uk/component-guide` URL (for example, `frontend.dev.gov.uk/component-guide/`)
2. Open the browser console
3. Run `window.GOVUK.VisualDiffTool()`

An error similar to the following should appear:

> `Refused to frame 'https://frontend.herokuapp.com/' because it violates the following Content Security Policy directive: "frame-src 'self' *.publishing.service.gov.uk *.dev.gov.uk www.gov.uk www.youtube.com www.youtube-nocookie.com".`

**Comment by alex-ju** [comment]
Shall we consider deprecating `VisualDiffTool`? Especially now that we have a new way of doing VR. I don't think anyone is using it at the moment.

**Comment by injms** [comment]
Deprecating this sounds okay to me if no one is using it. It's a neat idea, but pointless having it around if it's not working and not being used.
