### ISSUE TITLE
External links events don't work for links to National Archives

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2054]
There are many links to content that's been moved to the National Archives. These can have the original www.gov.uk URL appended on the end, for example:

 - https://webarchive.nationalarchives.gov.uk/*/https://www.gov.uk/guidance/claim-for-wage-costs-through-the-coronavirus-job-retention-scheme
 - http://webarchive.nationalarchives.gov.uk/20160610100628/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/516279/tsrgd-2002-t-tourist-symbol-drawings.zip

These links don't currently fire the "external link clicked" event, as they get misdiagnosed as an internal link by this selector in the [`external-link-tracker.js`](https://github.com/alphagov/govuk_publishing_components/blob/f412b83d650453dfd4fde0ee03ad3862ac998141/app/assets/javascripts/govuk_publishing_components/analytics/external-link-tracker.js#L12):
```js
'a[href^="http"]:not(a[href*="' + window.location.host + '"])'
```

Note: there are some National Archive links that do fire the "external link clicked" event, for example:

 - https://webarchive.nationalarchives.gov.uk/*//www.hmrc.gov.uk/manuals/rpsmmanual/RPSM10105110.htm
 - http://webarchive.nationalarchives.gov.uk/*/http://www.hmrc.gov.uk/ebu/p46-pension.pdf

They don't have `www.gov.uk` as part of the URL, so aren't excluded by the selector.

**Comment by andysellick** [comment]
We're now transitioning to GA4 (instead of UA). While this issue still exists in UA, I've tested it with the new code for GA4 and it doesn't have the same problem, so I'm closing this issue.
