### ISSUE TITLE
Propose Postcode lookup to be made a component

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#2096]
## What?

On my travels 😁 , I've noticed that the PostCode lookup pattern might be worthy of adding as a Component to the [gem](https://components.publishing.service.gov.uk/component-guide)

## Why?

The pattern is current in used in multiple places with various implementation patterns.  

Example pages:
- http://gov.uk/find-local-council
- https://www.gov.uk/landlord-immigration-check/y 
- https://www.gov.uk/contact-electoral-registration-office
- https://www.gov.uk/benefit-cap-calculator/y/yes/no/none/none/10.0/single
- https://www.gov.uk/coronavirus-local-help
- https://www.gov.uk/premises-licence
- https://www.gov.uk/temporary-events-notice
- https://www.gov.uk/apply-skip-permit
- https://www.gov.uk/street-collection-licence
- https://www.gov.uk/zoo-licence
- https://www.gov.uk/premises-licence-scotland
- https://www.gov.uk/house-to-house-collection-licence
- https://www.gov.uk/public-charitable-collection-permit-scotland
- https://www.gov.uk/late-hours-catering-licence-scotland
- https://www.gov.uk/food-business-registration
- https://www.gov.uk/cooling-tower-notification

![screenshot-www gov uk-2021 05 25-15_19_59](https://user-images.githubusercontent.com/71266765/119514689-241e9100-bd6d-11eb-826c-8f8b68ddffc8.png)

![screenshot-www gov uk-2021 05 25-15_19_47](https://user-images.githubusercontent.com/71266765/119514696-24b72780-bd6d-11eb-86a8-a01ed7d9a7ca.png)

![screenshot-www gov uk-2021 05 25-15_19_33](https://user-images.githubusercontent.com/71266765/119514700-254fbe00-bd6d-11eb-81b6-b72e3a2c78ce.png)

--- 

## Design System

At present the Design System suggests a pattern (similar to the screen shot) however it is also noted on the [backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/82): https://design-system.service.gov.uk/patterns/addresses/

![image](https://user-images.githubusercontent.com/71266765/119515208-91322680-bd6d-11eb-894a-c002b8efe135.png)

## Other notes

- The pattern would be a component comprised of other components including `fieldset`, `input`, `button` (an [organism](https://bradfrost.com/blog/post/atomic-web-design/) perhaps in this context)
- The grey box has mentioned as perhaps an out-of-date design
- Many current input fields have a width that is too wide for the input of postcode.
- Letting the user set the default suggested postcode has been previously requested as a requirement due being London centric

**Comment by MartinJJones** [comment]
In a recent Accessibility Audit, an issue was reported on a page that used this pattern.

DAC_Usability_Error_Message_Components_03: Error message components do not conform with GOV.UK Design System guidelines

The page in question no longer uses the Postcode lookup pattern, but we can still access it using Wayback Machine - https://web.archive.org/web/20220308101555/https://www.gov.uk/test-and-trace-support-payment

Creating a new Postcode lookup component may help address the accessibility issue reported in all instances where the pattern is being used.

I have referenced this GitHub issue on the related Trello card - https://trello.com/c/GcUaola5/7-error-message-components-do-not-conform-with-govuk-design-system-guidelines-dacusabilityerrormessagecomponents03

**Comment by maxgds** [comment]
> In a recent Accessibility Audit, an issue was reported on a page that used this pattern.
> 
> DAC_Usability_Error_Message_Components_03: Error message components do not conform with GOV.UK Design System guidelines
> 
> The page in question no longer uses the Postcode lookup pattern, but we can still access it using Wayback Machine - https://web.archive.org/web/20220308101555/https://www.gov.uk/test-and-trace-support-payment
> 
> Creating a new Postcode lookup component may help address the accessibility issue reported in all instances where the pattern is being used.
> 
> I have referenced this GitHub issue on the related Trello card - https://trello.com/c/GcUaola5/7-error-message-components-do-not-conform-with-govuk-design-system-guidelines-dacusabilityerrormessagecomponents03

I think all the instances of this are using the same shared partial in a single app. The elements are all existing components, I'm not sure there's benefit to collating them into a new component, which I think might actually make it more complicated to apply the error warnings well, so I'm going to close this.
