### ISSUE TITLE
Cookie banner problem in IE10

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#2103]
Parts of the cookie banner that should be shown, hidden and updated as users interact with it aren't working properly in Internet Explorer 10. I think some of it is due to reliance on the `hidden` attribute, which [isn't supported in IE10](https://caniuse.com/hidden) but there may be other causes.

https://user-images.githubusercontent.com/861310/119979964-8963c380-bfb3-11eb-8e08-aedf30e8724e.mov

**Comment by danacotoran** [comment]
Should be fixed with the release of https://github.com/alphagov/govuk_publishing_components/pull/2231 so will be closing

**Comment by danacotoran** [comment]
#2231 had to be reverted, so I've reopened this for now

**Comment by MartinJJones** [comment]
Closing this issue as JavaScript no longer runs in IE10
