### ISSUE TITLE
Document list focus state sometimes missing underline

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2111]
The _[with only link]_ variation of the document list is missing the underline when focused:

![image](https://user-images.githubusercontent.com/1732331/120533817-0be7eb00-c3d9-11eb-8944-0ad257e1c8ab.png)

And the first example of the _[with context]_ variation is missing the focus state: 
![image](https://user-images.githubusercontent.com/1732331/120534043-4c476900-c3d9-11eb-92b2-6ecd79b2a68a.png)

but the second example is fine:
![image](https://user-images.githubusercontent.com/1732331/120534131-67b27400-c3d9-11eb-86a6-14aeeccfb016.png)

The expected behaviour would be for all of the focus states to have the black underline visible.

[with context]: https://components.publishing.service.gov.uk/component-guide/document_list/with_context
[with only link]: https://components.publishing.service.gov.uk/component-guide/document_list/with_only_link

**Comment by danacotoran** [comment]
Can't replicate this one. Which browser was this?

**Comment by andysellick** [comment]
@danacotoran it's possible this was fixed in https://github.com/alphagov/govuk_publishing_components/pull/2211

**Comment by injms** [comment]
I can't replicate in our supported browsers, so I it's fixed 👍
