### ISSUE TITLE
Global banner wrapper spacing issue (gem layout)

### ISSUE THREAD

**Issue by danacotoran** [alphagov/govuk_publishing_components#2159]
`.gem-c-layout-for-public__global-banner-wrapper` has a negative `margin-top` value. 
https://github.com/alphagov/govuk_publishing_components/blob/1dee4ae94c9187455bd5b5cf714e4bf5c0ef219f/app/assets/stylesheets/govuk_publishing_components/components/_layout-for-public.scss#L11 

This is fine when this element has content, for example on pages where the global bar is present:  

<img width="1192" alt="Screenshot 2021-06-23 at 13 00 24" src="https://user-images.githubusercontent.com/7116819/123092999-ffc4db80-d422-11eb-9bc0-cb8861b9959c.png">

However, when the element is empty, a spacing issue seems to occur. Note in the screenshot below, on a page where the global bar is hidden, the padding on the Alpha banner is overlapping the blue bar below the header: 

<img width="1626" alt="Screenshot 2021-06-23 at 13 02 40" src="https://user-images.githubusercontent.com/7116819/123093268-65b16300-d423-11eb-95dd-8646e4cea7d8.png">

When the negative margin-top is removed from `.gem-c-layout-for-public__global-banner-wrapper`, the alpha banner appears as intended. 
<img width="1623" alt="Screenshot 2021-06-23 at 13 04 46" src="https://user-images.githubusercontent.com/7116819/123093532-b7f28400-d423-11eb-8803-648f94d2a8fe.png">

---- 
Not sure what the best solution is but I've opened this issue to record it for now 😕  (FYI @injms  as I think you've worked on this before)

**Comment by alex-ju** [comment]
I think I might have fixed this in https://github.com/alphagov/govuk_publishing_components/pull/2294, would you be able to have a look and close this if that's the case?

**Comment by danacotoran** [comment]
thanks a lot @alex-ju, I think you're correct, by the looks of it your PR should have fixed this 👏🏼
