### ISSUE TITLE
Mysterious crown logo misalignment

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2187]
## Problem:

The crown part of the logo was incorrectly aligned vertically:

![image](https://user-images.githubusercontent.com/1732331/124590952-a3ff4700-de53-11eb-9b9b-60c7886835c7.png)

A [small hack](https://github.com/alphagov/govuk_publishing_components/pull/2134) was used to shift the crown up by 1 pixel:

![image](https://user-images.githubusercontent.com/1732331/124591038-bbd6cb00-de53-11eb-9637-331d35222ce3.png)

This should be aligned correctly without any adjustment - see [@36degrees comment](https://github.com/alphagov/govuk_publishing_components/pull/2134#issuecomment-862358404) for further information.

**Comment by kr8n3r** [comment]
compare the height attribute on the SVG against the DS: 32 vs 30
