### ISSUE TITLE
Modernizr isn't needed

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#2240]
We have modernizr in the components gem but it only appears to be used on the admin layout, targeting browsers less than IE9. 

We should investigate whether we really need it and whether it can be removed.

It was introduced in this PR: https://github.com/alphagov/govuk_publishing_components/pull/422

**Comment by andysellick** [comment]
Admin layout isn't used on the public site - only in publishing applications (think just content-publisher and content-data) where users may be stuck using older browsers, so we should probably still support them.

**Comment by jon-kirwan** [comment]
I’m wondering if we might actually be able to remove Modernizr now.

The gem version of Modernizr has the following configuration:
- Flexbox
- Flexbox (tweener)
- History API
- html5 printshiv
- Add CSS classes (default)

I can’t find any 'no feature' styles configured for `no-flexbox` or `no-flexboxtweener` anywhere in the publishing applications (or for anywhere that uses the admin template). I searched for [no-flexbox](https://github.com/search?q=org%3Aalphagov+.no-flexbox+language%3ASCSS&type=code) and [no-flexboxtweener](https://github.com/search?q=org%3Aalphagov+.flexboxtweener+language%3ASCSS&type=code).
Same for the [History API](https://github.com/search?q=org%3Aalphagov+Modernizr.history&type=code)
Finally, there's the printshiv option (allowing HTML5 elements to be styled and contain children while being printed in IE 6-8). Is it safe to assume that printing admin pages in browsers older than IE9 isn't a major requirement?

The admin template is used by:
- Publisher
- Local Links Manager
- Places Manager (formerly Imminence)
- Collections Publisher
- Content Data Admin
- Manuals Publisher
- Search Admin.
