### ISSUE TITLE
Subscription links alignment while wrapped

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#2324]
## What

While reviewing [this PR](https://github.com/alphagov/whitehall/pull/6252/) noticed that the [subscription links](https://components.publishing.service.gov.uk/component-guide/subscription_links) while inside a `govuk-grid-column-one-third` could visually wrap in a better way so the icons / text line up vertically 

![image](https://user-images.githubusercontent.com/71266765/135064843-30c144e4-5c30-4078-98a9-9f60e58943dd.png)

## Suggested fix

The SVG or containing element could be the same width.

**Comment by andysellick** [comment]
After discussion among the team we've decided to close this issue as a won't fix.
