### ISSUE TITLE
Primary links js module is problematic

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk_publishing_components#2364]
## The problem
The [PrimaryLinks js module](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/govuk_publishing_components/lib/primary-links.js) is in need of some tidying up. There are 2 principal issues at play:

- The UI produced by this component isn't accessible. It produces a link which should be a button which itself disappears once clicked. There is no communication to screen reader users that the page has changed.
- How much it's used across govuk apps is dubious. We know it's being used in manuals frontend but it's unclear how much it's used elsewhere.

[Test page](https://www.gov.uk/guidance/drivers-hours-goods-vehicles/introduction#eu-countries)

[Example of use](https://www.gov.uk/jobseekers-allowance)

## proposed next steps
1. Rework the UI so that it's more accessible for assistive tech users
2. Assess where it's actually used across govuk
3. Depending on the outcome of 2, potentially remove primary links out of the gem

I'm personally skeptical as to how useful this function is and feel that work should be done to remove this feature from govspeak, steer publishers away from using it and retire this module all together. That however is a task for a team, not for this issue.

**Comment by owenatgov** [comment]
Update: I posted this to the design community channel and got some interesting suggestions but generally not much in the way of concrete ideas of how to design this problem away. I'm going to therefore suggest the scope of this issue be to remove it from the components gem, not necessarily fix the accessibility problem.

Things I'm going to aim to do next:

1. Query the content store to check how many pages are using this feature
2. Consider dropping some analytics on this feature to assess how often it's used by users

**Comment by owenatgov** [comment]
After a publishing API query, here are all the pages that this feature is being used excluding 404's:
- https://gov.uk/cma-cases/cineworld-city-screen-merger-inquiry
- https://gov.uk/cma-cases/ericsson-creative-merger-inquiry
- https://gov.uk/guidance/drivers-hours-passenger-vehicles/annex-1-legislation
- https://gov.uk/guidance/drivers-hours-goods-vehicles/annex-1-legislation
- https://gov.uk/guidance/drivers-hours-goods-vehicles/introduction
- https://gov.uk/guidance/drivers-hours-passenger-vehicles/introduction

Most of these are manuals, however something interesting is that the first 2 are from government frontend. These were published in 2014 and 2015 back when primary links were still in govuk_toolkit via static and thus everywhere. Based on the fact that neither of these have been reported in 6+ years, I'm feeling comfortable with moving this to only manuals frontend. I'm going to ask about this in the content community channel first to see if there's a chance for us to just retire it.

**Comment by owenatgov** [comment]
Suggestion from @alex-ju:

Talk to folks in relevant content teams (rainbow team) to see who's working with CMA and DVSA to let them know.

**Comment by MartinJJones** [comment]
## PrimaryLinks module to be removed
After looking into this issue and following on from the comments above, the `PrimaryLinks` module will be removed. The 4 pull requests below will remove the `PrimaryLinks` JS module and the govspeak function `PriorityList` used to generate the HTML for the `PrimaryLinks` module.

- [Remove PrimaryLinks JS Module from `govuk-publishing-components`](https://github.com/alphagov/govuk_publishing_components/pull/2866)
- [Remove PriorityList from `govspeak`](https://github.com/alphagov/govspeak/pull/249)
- [Remove initialisation of the PrimaryLinks JS Module from `manuals-publisher`](https://github.com/alphagov/manuals-publisher/pull/1909)
- [Remove Priority List example from `govuk-admin-template`](https://github.com/alphagov/govuk_admin_template/pull/247)

## Why
The "PrimaryLinks" module is not accessible and not widely used across GOVUK.

After searching the content store for the `primary-item` CSS class which is used by the PrimaryLinks module, 28 items were found. All of the 28 items used the "government-frontend" rendering app, however the "government-frontend" app does not initialise the PrimaryLinks module, so has no impact on how these pages are rendered.

### Breakdown of content items found
**CMA content - 24 pages**
The PrimaryLinks module has not worked on these pages for over 5 years, following the migration of "Specialist Frontend" to "Government Frontend".

**DVSA content - 4 pages**
The Primary Links module for these pages stopped working a couple of months ago following the migration of "Manuals Frontend" to "Government Frontend".

## Further information
The Pull Requests above and the Trello card include further information relating to the change.
Trello: https://trello.com/c/Vl2qEqFw/1353-review-the-track-result-module-and-requirements

**Comment by kevindew** [comment]
Thanks for digging into this @MartinJJones looks really thorough.

So if I understand right the consequences of removing this will have zero visual impact on the pages as they are currently not using the JS and just displaying normal lists.

I assume we've got a situation where, if someone created a new edition of any of the content - or if we republished the existing items - that there would be visual problems because Govspeak would no longer know how to convert PriorityList and thus leave some odd things in the output. Is that correct? and have we pondered resolving that (for what it's worth we could probably convert them to a regular list before removing Govspeak)

Also it looks like we advise publishers that they should use this feature on: https://www.gov.uk/guidance/how-to-publish-on-gov-uk/markdown so we'll want to coordinate so the guidance can be dropped and, if appropriate, inform publishers that a feature is being removed.

**Comment by kevindew** [comment]
Super - that list sounds great.

**Comment by MartinJJones** [comment]
Closing this issue as the PrimaryLinks JS Module was removed from govuk-publishing-components:

- [Remove PrimaryLinks JS Module from `govuk-publishing-components`](https://github.com/alphagov/govuk_publishing_components/pull/2866)
- [Remove PriorityList from `govspeak`](https://github.com/alphagov/govspeak/pull/249)
- [Remove initialisation of the PrimaryLinks JS Module from `manuals-publisher`](https://github.com/alphagov/manuals-publisher/pull/1909)
- [Remove Priority List example from `govuk-admin-template`](https://github.com/alphagov/govuk_admin_template/pull/247)
