### ISSUE TITLE
Navigation header doesn't finish rendering if JS errors

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#2367]
Spotted this while developing locally with `government-frontend`. I'd broken the scroll tracking JavaScript and when the page rendered it looked like this:

![Screenshot 2021-10-15 at 09 29 26](https://user-images.githubusercontent.com/861310/137457468-068fc575-34c7-4af6-837f-5e8519cc9392.png)

This was in development and hopefully we'd catch any obvious JS errors like this before going to production, but it's always possible that a JS error like this could occur for another reason (we get loads of JS errors in LUX which seem to be due to things like conflicts with browser extensions, or if someone's connection dies mid-download, for example).

(apologies for the nebulous 'this might break bye' issue, but I thought it would be worth recording edge cases like this)

**Comment by injms** [comment]
Just to make sure that this isn't missed, this concerns the [navigation header](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) component.

**Comment by injms** [comment]
We found that this has been fixed in https://github.com/alphagov/govuk_publishing_components/pull/2388.

Separately, I'm going to see if there could be further improvements to the way this component loads and initialises.
