### ISSUE TITLE
Navigation header menu potentially visible on slow devices during page load

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#2368]
I've glimpsed this a few times when developing. The [new header menu](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) can be briefly visible while the page is loading. See below, this was recorded using Chrome's devtools to throttle CPU x6 and network to 'slow 3G'.

https://user-images.githubusercontent.com/861310/137466426-0e7eff26-edaa-4519-8e1c-6e7ef32f663b.mov

I'm not sure how big a problem this might be but thought it worth documenting. I had to use my mobile this week while out and about with poor signal was reminded how important this stuff is.

**Comment by chao-xian** [comment]
Tracking on https://trello.com/c/ClqbBLEX/579-header-menu-potentially-visible-on-slow-devices-during-page-load
