### ISSUE TITLE
Organisation colour for Department for Levelling Up, Housing and Communities (DLUHC) can be removed when it's updated in GOV.UK Frontend

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2455]
The DLUHC organisation colour needed to be added to the gem - which was done in https://github.com/alphagov/govuk_publishing_components/pull/2454.

This can be removed when the change is also made to GOV.UK Frontend (https://github.com/alphagov/govuk-frontend/pull/2434), it's released, and then bumped in the gem.

Done when:

- [x] DLUHC colour is added to GOV.UK Frontend
- [x] New version of GOV.UK Frontend released with DLUHC org colour
- [x] GOV.UK Frontend is bumped in the gem
- [x] Changes in https://github.com/alphagov/govuk_publishing_components/pull/2454 removed

**Comment by jon-kirwan** [comment]
Bumped to GOV.UK Frontend v4.0.0 in https://github.com/alphagov/govuk_publishing_components/commit/8fa7c55389c1fac80dafc45bfe1e3ab85264fb33

**Comment by jon-kirwan** [comment]
Change removed here: https://github.com/alphagov/govuk_publishing_components/commit/a1b023be2ef1498562f4de72031ea04166389e5b
