### ISSUE TITLE
Help us improve component has incorrect gutters on small screens.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#251]
<img width="397" alt="screen shot 2018-03-27 at 15 29 37" src="https://user-images.githubusercontent.com/2445413/37974019-b907f8b6-31d3-11e8-8b82-d08dac84feac.png">

**Comment by tijmenb** [comment]
https://trello.com/c/bHQg59XJ/257-help-us-improve-component-has-incorrect-gutters-on-small-screens
