### ISSUE TITLE
Very small text on document list component on small screens

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#252]
Noticed this while browsing https://www.gov.uk/education/further-education-funding

<img width="330" alt="screen shot 2018-03-27 at 15 35 08" src="https://user-images.githubusercontent.com/2445413/37974319-89d2836c-31d4-11e8-815a-315ce10221e0.png">

The font size is 12px which feels lower than it should be, making the text harder to read.

**Comment by tijmenb** [comment]
https://trello.com/c/MUTHaInl/256-very-small-text-on-document-list-component-on-small-screens
