### ISSUE TITLE
Missing empty email address validation in feedback component

### ISSUE THREAD

**Issue by gclssvglx** [alphagov/govuk_publishing_components#2539]
When a user clicks the 'No' button on "Is this page useful?" they get an offer to be emailed a link to the survey.

![146791089-7d6ad90e-ddc1-412a-9086-2f3c4fe5d260](https://user-images.githubusercontent.com/44037625/147077394-7f8fe9b1-2f27-4cb5-807b-e28b6fce3c78.png)

But if they leave the 'Email address' field empty and click the green 'Send me the survey' button, they don't get an error/hint, just a Thank you message.

![146791274-197a6d5e-bdf7-4e0c-a234-5809fe8160ef](https://user-images.githubusercontent.com/44037625/147077426-98b1ada3-b350-41b9-948d-b231019276a5.png)

On the frontend, the feedback component displays a success message only if status code 200 is returned, which seems to be what is happening when an empty email field is submitted. When server side validation for email address has failed, the response status code should probably be a 400 with an error message attached.

Zendesk ticket where this was reported originally https://govuk.zendesk.com/agent/tickets/4786005

**Comment by MartinJJones** [comment]
Closing this issue as the feedback component no longer uses an input field.
<img width="1174" alt="Screenshot 2024-09-12 at 11 16 53" src="https://github.com/user-attachments/assets/6fca9a94-cfec-4537-a7ae-ef68cc84e093">
