### ISSUE TITLE
Jasmine Ruby gem is EOL

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk_publishing_components#2555]
3.99 is the final version of Jasmine for Ruby. We'll have to consider whether to migrate to `jasmine-browser-runner` npm package (which is the direct replacement for the `jasmine` gem) or use the `jasmine` npm package and run specs in NodeJS

_Originally posted by @alex-ju in https://github.com/alphagov/govuk_publishing_components/pull/2545#pullrequestreview-846667200_

**Comment by kevindew** [comment]
Good shout opening this. I keep seeing signs of it and thinking 😱 

I'd be keen to get involved in working out what we do about this and our plan going forward. I feel perhaps that once we get rid of jQuery we might want to see about how we modernise JS testing or even modernise our JS in general.

**Comment by alex-ju** [comment]
Thanks @kevindew and @ollietreend for getting involved with this!
