### ISSUE TITLE
Update details icon

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#2608]
## What

[Details](https://components.publishing.service.gov.uk/component-guide/details/default/preview) iconography to align to [Accordion](https://components.publishing.service.gov.uk/component-guide/accordion) & [Step-by-Step ](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav)

## Mock
Before > After

![side by side of details element, this has an icon update where the icons on before is a solid triangle, while the updated icon is a chevron within a circle](https://user-images.githubusercontent.com/71266765/152526832-c7e9e85e-f5b4-48f9-8cb1-b52cf5ddb484.jpg)

**Comment by andysellick** [comment]
The Design System [currently doesn't use this icon](https://design-system.service.gov.uk/components/details/). I understand that consistency is good but while the details component functions like a single part of an accordion it's otherwise visually distinct, so I'm not sure I understand the need for such a change. Can you explain?

**Comment by chris-gds** [comment]
Sure, it ties into [3.2.4 consistency](
https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification.html ) and user expectations. In this example this icon indicates that the element will "open and close"

_Example 1: Document Icon_

_A document icon is used to indicate document download throughout a site. The text alternative for the icon always begins with the word “Download," followed by a shortened form of the document title. Using different text alternatives to identify document names for different documents is a consistent use of text alternatives._

_Example 4: Icons with similar functions_

> The Design System [currently doesn't use this icon](https://design-system.service.gov.uk/components/details/).

This is a good point 🤔 this might be more apt to raise this there.

**Comment by chris-gds** [comment]
After having a think / chat -  when the gem updates to `gov-frontend 4.0` this absorbs the `details` element, if it was to update it would be better placed coming from here as it would flow through into the gem.  I'm going to close this and capture it there for future.

**Comment by chris-gds** [comment]
Captured here for future ref: https://github.com/alphagov/govuk-frontend/issues/2531
