### ISSUE TITLE
Switch from `master` to `main` branch

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2640]
We should switch this repo to use the `main` branch as the name for the primary branch to match the other repositories being used for GOV.UK

- [x] Change `ci.yml` workflow to detect if on the `main` branch rather than the `master` branch for publishing the gem
- [x] [Rename the `master` branch to `main`][1]
- [x] [Update Heroku deployment](https://help.heroku.com/O0EXQZTA/how-do-i-switch-branches-from-master-to-main) to look for `main` rather than `master`
- [x] Let everyone know that they need to update their local branch to `main`

Taken from [_How to switch a Git default branch from master to main_][2], omitting:
 - Jenkins, as this repo no longer uses Jenkins
 - Updating the release app, since it's not used to release this application

[1]: https://github.com/github/renaming#renaming-existing-branches

[2]: https://docs.publishing.service.gov.uk/manual/howto-switch-default-branch.html

**Comment by injms** [comment]
I've raised a pull request to update the GitHub Actions workflow: https://github.com/alphagov/govuk_publishing_components/pull/2639

**Comment by injms** [comment]
The tasks have been completed - but I think this should be closed only when a gem has been successfully released from the `main` branch.

**Comment by alex-ju** [comment]
We've had two releases since then – both went fine
