### ISSUE TITLE
Add GA testing for the Accordion

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#2694]
## What

Add tests for GA (Google Analytics) "Show all sections" and each individual section tracking for the Accordion.

## Why

As [part of this PR](https://github.com/alphagov/govuk_publishing_components/pull/2693) click-event-tracking has been added the Accordion so when a user interacts with "Show all sections" or an individual section this can be sent to GA. These are behind feature flags.

However testing needs to be added, the [Accordion testing](https://github.com/alphagov/govuk_publishing_components/pull/2647) moves away from testing a [copy of the HTML](https://github.com/alphagov/govuk_publishing_components/blob/854fff8aaf88d7ae56b10782cbd78a937e36e5cb/spec/javascripts/components/checkboxes-spec.js#L10) and tests against the [actual rendered component making the test more accurate](ttps://github.com/alphagov/govuk_publishing_components/blob/main/spec/features/accordion_spec.rb). However for the context of this PR partially restoring the Jasmine test GA is required

Ideally we need to 

- [ ] Restore Jasmine (`accordion-spec.js`) file
- [ ] Extend the tests to ensure that tracking works as expected.

(An alternative approach would be add GA to the `dummy_app` and testing against that).

`http://govuk-publishing-components.dev.gov.uk/accordionexample`
[Conversation happening here](https://github.com/alphagov/govuk_publishing_components/pull/2693#discussion_r833112377)

## Anything else

Draft WiP PR is here

**Comment by jon-kirwan** [comment]
Closing as the Accordion component has tracking (for both showing all sections and tracking each individual section), accompanied by an `spec.js` file. Additionally, the problem seems to be related to Universal Tracking, which is now deprecated.
