### ISSUE TITLE
Update list with tracking

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk_publishing_components#2703]
## What

Extend [list component](https://components.publishing.service.gov.uk/component-guide/list) to use accept tracking values

## Why

At present it's not possible to pass GA tracking to this component.

## Anything else

Separate issue: it would be good to alter the `sanitize` system to make it more readable when passing values.

**Comment by andysellick** [comment]
Closing this as no one has claimed a requirement for it and we're about to rework all of the tracking stuff anyway.
