### ISSUE TITLE
Organisation logo component doesn’t expand for long lines of organisation names

### ISSUE THREAD

**Issue by wilsond-gds** [alphagov/govuk_publishing_components#2768]
## Description of issue

On the [Ukranian welcome guidance page](https://www.gov.uk/government/publications/welcome-a-guide-for-ukrainians-arriving-in-the-uk/week-one-guidance-for-ukrainians-arriving-in-the-uk) the DLUC logo introduces extra line breaks apart from those indicated in the source code: see screenshot below
![breaking-page](https://user-images.githubusercontent.com/101639632/168047620-6c541fce-8d7a-432f-bb4d-ad2245cc2ee1.png)

## Possible solutions

Currently it's difficult to tell if this is an issue with font rendering on different devices (e.g. different versions of Helvetica) but the problem can be fixed by adding `flex-grow:1` to the CSS for `.organisation-logos__logo`: currently only `flex-basis` is set (which may not set `flex-grow` and `flex-shrink`?). 

If this is not possible setting `flex-basis:33%` will also produce the intended visual rendering.

See screenshot below.

![page-fix](https://user-images.githubusercontent.com/101639632/168048200-2bcb4e4b-93c7-43be-bbe5-47b898fca5a8.png)

**Comment by injms** [comment]
This looks a good fix - we'll need to check with the department to make sure that the layout is fine with them.

**Comment by jon-kirwan** [comment]
I'm closing the issue; it looks like the formatting has now been fixed. There is an option in Whitehall to provide a formatted title for organisation names -

```
"logo": {
"crest": "single-identity",
"formatted_title": "Department for Levelling Up,<br/>Housing &amp; Communities"
},
```

![whitehall-admin integration publishing service gov uk_government_admin_organisations_department-for-levelling-up-housing-and-communities_edit(iPad Pro)](https://github.com/alphagov/govuk_publishing_components/assets/87758239/e53409c5-bbd5-48b2-a5a2-51e56c2402f0)

![www gov uk_government_organisations_department-for-levelling-up-housing-and-communities(iPad Pro)](https://github.com/alphagov/govuk_publishing_components/assets/87758239/11e38417-b264-4d8c-ba35-7805b0962e48)
