### ISSUE TITLE
Review how node modules are kept up-to-date

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/govuk_publishing_components#2815]
## What

We currently have the node modules below as dependencies in `package.json` that are not being upgraded when releasing the publishing components gem.

| Node Module | Current version | After running `yarn upgrade` | Latest version | comments |
| - | - | - | - | - |
| axe-core | 3.5.4 (2020-05-27) | 3.5.6 (2021-06-16) | 4.4.2 (2022-05-12) | [Last updated by dependabot-preview](https://github.com/alphagov/govuk_publishing_components/commit/4c9cb8ce7d84c50bd279ba06994740104c24f2c9) |
| sortablejs | 1.13.0 (2021-01-08) | 1.15.0 (2022-03-20) | 1.15.0 (2022-03-20) | |
| @percy/cli | 1.0.0-beta.73 (2022-01-13) | 1.3.0 (2022-06-06) | 1.3.0 (2022-06-06) | |
| stylelint-config-gds | 0.2.0 (2022-03-28) | 0.2.0 (2022-03-28) | 0.2.0 (2022-03-28) | |
| postcss | 8.4.14 (2022-03-16) | 8.4.14 (2022-03-16)| 8.4.14 (2022-03-16) | Stylelint depends on postcss, dependabot will also update postcss |

The current guidance states that we should run the `yarn install` command, however this does not upgrade any of the modules listed as the versions are locked in the `yarn.lock` file.

**Publish/release a new version of the gem documentation**
https://github.com/alphagov/govuk_publishing_components/blob/main/docs/publishing-to-rubygems.md

### Config

**dependabot.yml**
https://github.com/alphagov/govuk_publishing_components/blob/main/.github/dependabot.yml

**package.json**
https://github.com/alphagov/govuk_publishing_components/blob/main/package.json

### How to upgrade

We would instead need to run `yarn upgrade` to upgrade the modules within the accepted ranges. When this command is run, it will also update the `yarn.lock` file which would need to be committed.

**Note**: this does not update the package.json file in the same way dependabot does.

For example:

**dependabot also updates the package.json**
Upgrading to version 4.1.0 of govuk-frontend
`"govuk-frontend": "^4.1.0"`

**yarn upgrade does not update the package.json**
Upgrading to version 4.1.0 of govuk-frontend
`"govuk-frontend": "^4.0.1"`

## Questions
- If we do run `yarn upgrade`, should we also update package.json to be consistent with the dependabot approach
- How do we handle/monitor major version upgrades?

**Comment by kevindew** [comment]
Thanks for putting together an issue 👍 

In theory these shouldn't be upgraded at the point of issuing a release as we wouldn't have tested them. We'd want the upgrades to happen as a distinct part of repo management.

As you say we already have the dependabot process to keep dependencies up to-date. And for this repo we actively monitor dependencies for the following packages: [stylelint-config-gds, jasmine-browser-runner, jasmine-core, stylelint and standardx](https://github.com/alphagov/govuk_publishing_components/blob/d79f7433922f1ab6a4532b9fcc7cac40c44a851f/.github/dependabot.yml#L32-L50) and for other packages we'll just security updates. We may well want to revise that list, for example I'd imagine we'd very much like to stay up-to-date with percy. The argument against adding everything to the list is that it can be annoying to have lots of PRs, particularly if we don't need to be on the newest version - but it is indeed a risk if we never update things - a periodic yarn upgrade would probably be good.
