### ISSUE TITLE
🏞 Image card component - image lacks `width` and `height` attribute

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#2863]
The image in the image card component doesn't currently have the ability to use the `width` and `height` attribute; at the moment the image markup looks like this:

```html
<img 
  alt="" 
  class="gem-c-image-card__image"
  loading="lazy" 
  sizes="(max-width: 640px) 100vw, (max-width: 1020px) 33vw, 300px" 
  src="image-promo.jpg"
  srcset="image-promo.jpg 610w, image-promo-480.jpg 480w, image-promo-320.jpg 320w, image-promo-240.jpg 240w, image-promo-170.jpg 170w" 
/>
```

Setting a width and a height will allow the browser to know how much space the image should take up. Browsers use these dimensions to calculate the image's aspect ratio and reserve the space needed in the page layout - this reduces the amount of layout shift on the page.[^1]

The width and height are overridden by the page by the presence of any CSS targeting the image - as the image card component has styles for the image, this won't affect the visual presentation once loaded. But this should make the experience whilst the page is loading better as it will help avoid page jank aka cumulative layout shift.

As GOVUK (should) only be using images with a 3:2 aspect ratio[^2], this could be hardcoded into the component rather than added as an extra option. Because it's only the aspect ratio that the browser requires - not the actual pixel values of the image - the values could be set to just 300 and 200.

[^1]: For more details on why setting the `width` and `height` attribute is a good thing, see [Optimize Cumulative Layout Shift: Images without dimensions](https://web.dev/optimize-cls/#images-without-dimensions).
[^2]: https://design-system.service.gov.uk/styles/images/#aspect-ratio

**Comment by jon-kirwan** [comment]
I've re-opened the issue as unfortunately the fixed width and height attributes are leading to incorrectly sized images in some places:

![www gov uk_government_organisations_attorney-generals-office (1)](https://user-images.githubusercontent.com/87758239/180800188-cb5060fb-53bd-46ca-b1bf-5328a37e7d48.png)
![www gov uk_government_organisations_attorney-generals-office](https://user-images.githubusercontent.com/87758239/180800236-5009377e-a532-4cf5-b594-1190e7bb8557.png)
