### ISSUE TITLE
Print stylesheets are separate from screen stylesheets

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#3005]
Stylesheets imported from GOV.UK Frontend contain both screen and print styles in the same file:

[Example](https://github.com/alphagov/govuk-frontend/blob/cdd027bef7fbbea83756e514808cbde00f46aa2e/src/govuk/helpers/_typography.scss#L30-L32):

```scss
@mixin govuk-typography-common($font-family: $govuk-font-family) {

   ...

  @include govuk-media-query($media-type: print) {
    font-family: $govuk-font-family-print;
  }
}
```

Stylesheets for components in this gem have separate files for print and screen, for example:
+ [print/_accordion.scss](https://github.com/alphagov/govuk_publishing_components/blob/282383794b148a13cba3fb9236f4a081ff07b814/app/assets/stylesheets/govuk_publishing_components/components/print/_accordion.scss)
+ [_accordion.scss](https://github.com/alphagov/govuk_publishing_components/blob/282383794b148a13cba3fb9236f4a081ff07b814/app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss)

This means that the component gem contains stylesheets which have both rules for print and screen, and stylesheets that are only print.

This isn't breaking things because the non-print stylesheets are included with `media="all"` - but this is confusing.

I'd suggest that the component gem stylesheets should mirror the behaviour of GOV.UK Frontend, and have both screen and print stylesheets in the same file. This is a better option than trying to separate the print and screen styles out of GOV.UK Frontend, as that's very difficult / almost impossible.

Positives:
+ Easier to add print styles to a component, since the print stylesheet doesn't need to be manually added to a rendering application
+ Good to follow GOV.UK Frontend's lead on this - separating their styles into screen and print would be very difficult
+ One less concurrent download
+ No way for devs to forget to include the print CSS when they bring a new component into a rendering application

Negatives:
- much more difficult to audit which components have print stylesheets
- this isn't broken, so does it need fixing?

**Comment by maxgds** [comment]
We discussed this previoiusly and people seemed generally positive about it - I can't recall whether we foresaw any potential issues and my bad for not actually writing it up. I'd add to the positives:
1 less concurrent download
No way for devs to forget to include the print css when they bring a new component into a rendering app
