### ISSUE TITLE
Native implementation of search cancel button doesn't response to browser zoom

### ISSUE THREAD

**Issue by monicacrusellasfanlo** [alphagov/govuk_publishing_components#3086]
Hi there!

When you do browser zoom, the search cancel button doesn't scale properly and it looks tiny (see screenshot). The issue happens in Chrome and Safari.
<img width="1743" alt="Screenshot 2022-11-25 at 15 47 11" src="https://user-images.githubusercontent.com/106598959/204019401-8f0f6efa-b295-4226-9ea4-947d3489a240.png">

Since we are looking at this, could we consider overriding the cancel button style so it looks like the close icon used in the[ layout super navigation header ](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header)

For example, I see that Google uses their own style on their search bar. Here's an article that mentions how we could potentially do this: https://stackoverflow.com/questions/22928819/override-the-webkit-search-cancel-button

Thanks

**Comment by andysellick** [comment]
This is a problem in other browsers too (e.g. Edge) so there's a question over whether we'd have to solve this on a per-browser basis, or whether there's a solution for all browsers (which would allow for any new browsers as well).

**Comment by monicacrusellasfanlo** [comment]
Are there any updates on this one? I think what you suggest in your last comment makes sense, we should look at fixing it for all browsers. I am not sure what's the best solution to solve it across browsers, I wonder if using our own icon would help.

**Comment by AshGDS** [comment]
@monicacrusellasfanlo It looks like it's a browser bug. I can fix it by adding a `scale` to the cancel button, but it will look a bit blurry and the scale will only change at certain breakpoints.

**Comment by AshGDS** [comment]
@monicacrusellasfanlo Sorry looking at this now and just realised we could replace it with our own SVG instead of what I commented above. The X on our header menu is actually a text character, so is there an SVG you'd like to use for this?

**Comment by AshGDS** [comment]
Hi @monicacrusellasfanlo - do you have a recommendation on what SVG we could use for this? Thanks!

**Comment by AshGDS** [comment]
Sorry just coming back to this and was getting confused! Initially it looks like the header has an "X" SVG, but it is just a text character. @monicacrusellasfanlo do you have any suggestions on an SVG to use?
