### ISSUE TITLE
Showing the search menu causes horizontal overflow on desktop

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/govuk_publishing_components#3192]
## Issue

Showing the search menu causes horizontal overflow on desktop (> 768px)

The screenshot below shows a visible horizontal scroll bar in Firefox when the site search menu is open:

<img width="1391" alt="firefox-site-search-horizontal-menu" src="https://user-images.githubusercontent.com/28779939/212903147-361a3c75-d6af-40e0-b400-979491c50813.png">

The red outline in the screenshot was added to using dev tools to show the element that is likely causing the issue, `id="super-search-menu"`

## How to reproduce the issue

- Using any browser, visit any page on GOV.UK
- Ensure viewport width is larger than 768px
- Open the site search menu
- The horizontal scrollbar will then be shown in Safari and Firefox. The horizontal scrollbar is added to Chrome, but you may need to use the left/right arrow keys to scroll horizontally, it was hidden for me.

**Comment by patrickpatrickpatrick** [comment]
Will be solved by this PR https://github.com/alphagov/govuk_publishing_components/pull/3201

**Comment by patrickpatrickpatrick** [comment]
I never closed this issue, sorry about that. This has been solved by https://github.com/alphagov/govuk_publishing_components/pull/3201.
