### ISSUE TITLE
Content in the site search dropdown is not aligned when viewport width is `>768px` and `<1020px`

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/govuk_publishing_components#3194]
Content in the site search menu is not aligned when you are using a viewport width between `768px` and `1020px`.

The screenshot below shows an example of the issue:

<img width="983" alt="search-content-not-aligned" src="https://user-images.githubusercontent.com/28779939/212928252-dfe489b6-8aa8-4d6e-a530-117b4f9c629e.png">

**Comment by patrickpatrickpatrick** [comment]
Should be fixed by https://github.com/alphagov/govuk_publishing_components/pull/3201

**Comment by patrickpatrickpatrick** [comment]
Was fixed by https://github.com/alphagov/govuk_publishing_components/pull/3201. Sorry I didn't close this issue!
