### ISSUE TITLE
Investigate value of summary card component

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#3231]
The [recent addition](https://github.com/alphagov/govuk_publishing_components/pull/3222) of `govuk-frontend` 4.5.0 to `govuk_publishing_components` introduced the [summary card](https://design-system.service.gov.uk/components/summary-list/#summary-cards) extension of summary lists. 

This could be something useful for us to include, either as a new component or an extension of the existing summary list.

**Comment by andysellick** [comment]
@maxgds to check and see if we have a use case for this already.

**Comment by maxgds** [comment]
I found the examples I was thinking of and they're not a good fit: https://www.gov.uk/check-uk-visa/y/austria/work/longer_than_six_months/other so I'll close this.
