### ISSUE TITLE
Attachment renders differently when embedded inside Govspeak

### ISSUE THREAD

**Issue by ollietreend** [alphagov/govuk_publishing_components#3536]
The [Attachment component][1] renders slightly differently when it's [embedded inside Govspeak][2].

The most visible difference is that the "Request an accessible format." option is not styled as a hyperlink. However when jumping directly between the two, it also looks like there are slight differences in the line heights or spacing of text.

### Screenshots

| Standalone attachment | Embedded in Govspeak content |
| --- | --- |
| <img width="627" alt="Outside Govspeak" src="https://github.com/alphagov/govuk_publishing_components/assets/7735945/2a3f84c4-dd50-4793-86d1-5ffff5c3d9cf"> | <img width="627" alt="Inside Govspeak" src="https://github.com/alphagov/govuk_publishing_components/assets/7735945/67d6a284-842f-4e37-9a45-e94183037d85"> |

### Visual diff

![visual diff](https://github.com/alphagov/govuk_publishing_components/assets/7735945/5f0c21ff-f3df-4d62-aa95-4d746340a857)

### Examples on GOV.UK

This page contains standalone attachments (i.e. they're not embedded inside Govspeak content):
https://www.gov.uk/government/statistics/klebsiella-species-bacteraemia-monthly-data-by-location-of-onset

This page contains attachments embedded inside the Govspeak content:
https://www.gov.uk/government/news/report-072023-embankment-washout-under-a-passenger-train-at-haddiscoe

[1]: https://components.publishing.service.gov.uk/component-guide/attachment
[2]: https://components.publishing.service.gov.uk/component-guide/attachment/embedded_in_govspeak

**Comment by MartinJJones** [comment]
Closing this issue as it was fixed on this PR - https://github.com/alphagov/govuk_publishing_components/pull/3668

Thanks @andysellick for fixing 👍
