### ISSUE TITLE
Why does this gem contain more components than GOV.UK Frontend?

### ISSUE THREAD

**Issue by smith558** [alphagov/govuk_publishing_components#3735]
Why does this gem contain more components than GOV.UK Frontend? For example, https://components.publishing.service.gov.uk/component-guide/action_link, I cannot find this one in https://design-system.service.gov.uk/components/. There's more like that. How are `govuk_publishing_components` and the `govuk-frontend` related?

Why am I asking this? I would like to use the components from https://components.publishing.service.gov.uk/component-guide in a non-RoR project.

Thank you for your help!

**Comment by andysellick** [comment]
GOV.UK Frontend contains the code you need to start building a user interface for government platforms and services.

Like many other departments and services, we use GOV.UK Frontend on www.gov.uk. `govuk_publishing_components` is our way of doing that - by taking content from GOV.UK Frontend and turning it into a form we can use (in this case a Ruby on Rails gem).

Our extra components have been developed to fit the requirements of www.gov.uk. We also build on top of existing components from GOV.UK Frontend to provide needed variations.

If you wish to use this gem in your own application you are welcome to do so but we do not provide support to third parties.
