### ISSUE TITLE
Share tools copy-paste - pasted content has spacing issues.

### ISSUE THREAD

**Issue by KludgeKML** [alphagov/govuk_publishing_components#3844]
What

When a user copies and pastes from the share component, the pasted content has spacing issues, coming out as Share onFacebook(opens in new tab). There is slightly more detail on this zendesk ticket:

https://govuk.zendesk.com/agent/tickets/5312868

Why

Ideally the paste would maintain suitable spacing. This may be caused by the way the browser collapses whitespace and it’s possible we can’t fix this. However, if we can it would result in a nicer user experience for anyone wanting to paste the links. I believe that the user’s supposition that it looks wrong with images not loading is probably incorrect, but we should investigate.

If this is going to be difficult or impossible to fix then this ticket should be closed, potentially with a new one being opened. If it’s going to be simple to apply a fix then it can be implemented as part of this work.

Scoring

Problem Score = [0.5]
Priority (Total) Score = [1.5]

(Copied from this trello card for better visibility: https://trello.com/c/uZxxGUEZ/2094-ps15-examine-share-tools-copy-paste-issue)

**Comment by jon-kirwan** [comment]
Fixed by https://github.com/alphagov/govuk-frontend/commit/b28f809ccba174f5cffc0053d8619a7e646ff9af
