### ISSUE TITLE
Unable to throw an error to check if `GOVUK.analyticsPlugins.error` correctly sends information

### ISSUE THREAD

**Issue by injms** [alphagov/govuk_publishing_components#3921]
Both tests in question are turned of with`xit()`:
 - [it sends errors to Google Analytics](https://github.com/alphagov/static/blob/4ff74bda61bea670a2e55e44b924c81e2f3183c4/spec/javascripts/analytics_toolkit/error-tracking.spec.js#L18)
- [it tracks only errors with a matching or blank filename](https://github.com/alphagov/static/blob/4ff74bda61bea670a2e55e44b924c81e2f3183c4/spec/javascripts/analytics_toolkit/error-tracking.spec.js#L27)

Kudos to @andysellick for pretty much all of this.

### What we want to test

These tests should check if any JavaScript errors thrown are sent to Google Analytics. 

Testing if a function correctly throws an error is done using the `toThrow()` function. For example: `expect(triggerError()).toThrow(errorDetails)`. This won't work for these cases, since we're not interested in the error being thrown - we're interested in whether the analytics plugin is called to catch the error and whether it sends the correct information.

Consider the following pseudo-code example:
```javascript
analyticsPlugins.error() // sets up error listeners that point to trackEvent
analytics = { 
  trackEvent: function () {
    // event sent to Google Analytics
    // ...
  }
}
spyOn(analytics, 'trackEvent')

triggerError()
expect(analytics.trackEvent).toHaveBeenCalledWith(errorDetails)
```

When the error is thrown to see if `trackEvent()` is called, the test halts.

### Anonymous function

Putting `triggerError()` inside an anonymous function so it doesn't cause the entire test to halt means that it doesn't trigger `trackEvent()` because scope - so the test fails.

### Try / catch

Putting it in a `try`/`catch` block
```javascript
try {
  triggerError()
  expect(analytics.trackEvent).toHaveBeenCalledWith(errorDetails)
} catch(e) {
  // do something
}
```
doesn't work as the `catch` is called as soon as the error occurs - so `expect()` isn't run.

Moving the `expect()` function to the `catch` causes the test to halt as the error is caught by the block before `trackEvent()` can be called.

### `.callThrough()` 

Jasmine has a `.callThrough()` function - this didn't work, as it happens after the error has occurred and halted the tests.

### Stubbed `trackEvent` function

To check if the `trackEvent` was being called, the function was stubbed to change a global variable. This didn't work because anything that is supposed to happen after the error is thrown doesn't happen.

### Custom event

Thinking that the `error` event was causing the problem, a custom `xerror` event was created to be used instead of `error` - both in the spec and the `GOVUK.analyticsPlugins.error` function. Though the event was being fired and the data correctly passed into the event listener, the test failed as the `trackEvent` function wasn't being called.

( Basically `¯\_(ツ)_/¯` and `(ノಠ益ಠ)ノ彡┻━┻`. )

PR to include the analytics code from govuk_frontend_toolkit: https://github.com/alphagov/static/pull/1795

**Comment by MartinJJones** [comment]
@andysellick @AshGDS just wanted to check if this is still an issue or was `GOVUK.analyticsPlugins` removed when Universal Analytics was removed? thanks

**Comment by andysellick** [comment]
@MartinJJones thanks for pointing out - yes all of this code has now been removed so we can close this issue 🎉
