### ISSUE TITLE
Search component does not render correctly on mobile and tablet

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/govuk_publishing_components#4149]
## What

The label text in the [Search component](https://components.publishing.service.gov.uk/component-guide/search) on small screen sizes overlaps with the search button on small sizes

<img width="640" alt="Screenshot 2024-08-13 at 13 29 41" src="https://github.com/user-attachments/assets/760ff6ae-c249-455a-a545-1aa2d9a2897b">

A live example of this issue can seen in the service manual - https://www.gov.uk/service-manual/service-standard

**Comment by andysellick** [comment]
A quick fix for this is something like the following CSS, which will prevent the `.gem-c-search__label` element from overflowing:

```CSS
    max-width: 68%;
    text-overflow: ellipsis;
    max-height: 100%;
    overflow: hidden;
    white-space: nowrap;
```

Looking like this:

![Screenshot 2024-08-15 at 11 57 09](https://github.com/user-attachments/assets/f628a885-6fb1-460c-9a2d-127612787f99)

This is not ideal, though. Another approach would be to adjust the columns on the header, from this:

![Screenshot 2024-08-15 at 11 58 24](https://github.com/user-attachments/assets/89401df4-22be-4dd4-ba1d-ad8fa3e6cc24)

To this:

![Screenshot 2024-08-15 at 11 58 39](https://github.com/user-attachments/assets/eece7455-3fa0-4666-beca-47f46bc07301)

(included above is a suggested change to the text of the label, to make it more accurate as to what it actually searches)

**Comment by andysellick** [comment]
Noting also a problem in Firefox, when using the 'zoom text only' zoom option. My zoom is a little over 100% by default, and it looks like this:

<img width="1008" alt="Screenshot 2024-08-15 at 11 59 53" src="https://github.com/user-attachments/assets/d76c98a9-6851-4fc5-9fab-50246fa7e599">

It gets even worse as you zoom further:

<img width="993" alt="Screenshot 2024-08-15 at 12 00 06" src="https://github.com/user-attachments/assets/3d454866-f40c-425c-8a05-9610760bb5d3">
