### ISSUE TITLE
Layout header component options potentially no longer used

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#4153]
The [layout header component](https://components.publishing.service.gov.uk/component-guide/layout_header/) has a variation that I think is no longer used anywhere, since the work to improve the site header and make it consistent across the site in the last few years. This is the variant:

![Screenshot 2024-08-15 at 11 55 05](https://github.com/user-attachments/assets/2123f94a-397d-4419-b152-02c2c6895e10)

Would need a little investigation to just confirm this is no longer used anywhere, then remove it from the component.

**Comment by MartinJJones** [comment]
Agree that this variation can be removed, searching for the `search_left` option returns 0 results across alphagov - https://github.com/search?q=org%3Aalphagov+%22search_left%22+language%3AHTML%2BERB&type=code
