### ISSUE TITLE
Layout header does not toggle search component on mobile or tablet

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/govuk_publishing_components#4154]
## What

Clicking the search button does not toggle visibility of the search menu on screen widths <= 640px

A live example of this issue can seen in the service manual - https://www.gov.uk/service-manual/service-standard

**Comment by AshGDS** [comment]
I unintentionally fixed this before realising it was a separate issue card, so to fix it, it should just be a case of:

- Switching the `js-header-toggle` to `govuk-js-header-toggle` on the button.
- Adding `aria-controls='search'` to the button.
- Removing In `_layout-header.scss`, delete the `display: none` for `.gem-c-layout-header__search-form {` (line 151)

**Comment by MartinJJones** [comment]
That's great, thanks @AshGDS
