### ISSUE TITLE
Search title is cut off at certain screen sizes

### ISSUE THREAD

**Issue by ch-ncolley** [alphagov/govuk_publishing_components#4202]
On certain screen sizes the .UK in GOV.UK is cut off from the Search heading/label.

I noticed the example in the component guide doesnt use this nested heading approach so maybe this is why it was missed.

<img width="657" alt="GOV.UK Search screenshot with the .UK from GOV.UK is cut off on small" src="https://github.com/user-attachments/assets/ebabd171-cc4e-42cf-92e4-e9abde463117">

## Steps to reproduce
1. Go to https://www.gov.uk/search
2. Resize browser window to 650px

**Comment by andysellick** [comment]
Thanks for raising @ch-ncolley. This was a regression caused by a recent fix to a related problem. Will hopefully be able to deploy soon 👍
