### ISSUE TITLE
Search component breaks layout with increased font sizes

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk_publishing_components#4221]
If you increase the text size in your browser the search component input can expand below the height of the button, as shown (you can simulate this in Firefox with the 'zoom text only' option enabled, and zooming).

<img width="989" alt="Screenshot 2024-09-12 at 08 57 33" src="https://github.com/user-attachments/assets/e2d2f217-4b5a-4bc0-ac72-a719e871d106">

I had a quick go at fixing it and it might be possible to give the `.gem-c-search__submit` button element a position absolute and height of 100% to fix it, but I've not tested it in other browsers.

<img width="1007" alt="Screenshot 2024-09-12 at 09 02 05" src="https://github.com/user-attachments/assets/20d4eaf2-74a6-4b42-9c4b-6a2ff256043e">

Noticed as part of https://github.com/alphagov/govuk_publishing_components/pull/4218

**Comment by andysellick** [comment]
Definitely don't go with the fix I suggested above, because it does this with the new autocomplete...

![Screenshot 2024-09-12 at 12 51 00](https://github.com/user-attachments/assets/12c97d09-de14-457c-9a22-f6d5e52e3ec4)

**Comment by AshGDS** [comment]
Is this a duplicate of https://github.com/alphagov/govuk_publishing_components/issues/2498 ?

**Comment by andysellick** [comment]
Yep looks like, thanks, closing.
