### ISSUE TITLE
The contents list components gives very low visibility of which page in a list is active. 

### ISSUE THREAD

**Issue by ChristineWuerth** [alphagov/govuk_publishing_components#4262]
This is an issue someone raised with us in the process of documenting the contents list component as part of the design documentation work:
The components gives very low visibility of which page in a list is active. The way we show an active chapter is strange. I have an assumption that users might find it confusing – very little signal that a page you are on has changed. [See here](https://www.gov.uk/get-a-child-passport/replace-a-damaged-child-passport), is ‘replace a damaged child passport’ in the right place?

**Comment by andysellick** [comment]
@ChristineWuerth this issue is a little vague and feels like it would require some more research and probably some design work.
