### ISSUE TITLE
Add docs on how to setup a heroku app with reviews

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#55]

**Comment by fofr** [comment]
Probably one for govuk-developer-docs

**Comment by nickcolley** [comment]
Might be somewhat solved by https://github.com/alphagov/govuk_publishing_components/pull/56

**Comment by nickcolley** [comment]
Just need to cross link to https://docs.publishing.service.gov.uk/manual/review-apps.html

**Comment by nickcolley** [comment]
We now have

**Comment by tijmenb** [comment]
I think the page in the docs is enough. Most applications have review apps set up now, so the need to duplicate info in this gem is less. Feel free to reopen.
