### ISSUE TITLE
Metadata and document footer anchor link is too generic

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#600]
As seen in https://www.gov.uk/government/collections/new-a-level-and-as-level-qualifications-requirements-and-guidance#history

When pressing 'see all updates' in the metadata component, it'll anchor to some content in govspeak rather than the document footer component.

We could change this ID to be something more specific.

Related files:

- https://github.com/alphagov/static/blob/master/app/views/govuk_component/metadata.raw.html.erb#L39
- https://github.com/alphagov/static/blob/master/app/views/govuk_component/document_footer.raw.html.erb#L22

**Comment by owenatgov** [comment]
Would require an update to the [metadata component in the components gem](https://components.publishing.service.gov.uk/component-guide/metadata) and in the [publishing dates app component in government frontend](https://government-frontend.herokuapp.com/component-guide/published-dates).

There's research to suggest that this functionality might be a bit iffy so this might require a bit of more detailed design input in the future.
