### ISSUE TITLE
Component Principle additions

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#66]
I was thinking we should probably add something about:

- A components interface should mirror the DOM
- A components files should be colocated (govspeak is a good example that breaks this principle)
- A component should stay close to point of use -  dont make it a static component 'just incase', make it shared because you need to share it.

**Comment by tijmenb** [comment]
@nickcolley what do you mean by "A components interface should mirror the DOM"?

**Comment by nickcolley** [comment]
A component's interface for this project is the ERB partials' locals.

These locals are passed through to the partial which renders the component.

By picking locals that mirror the DOM, and keeping that consistent between components should make the partials can be more intuitive.

## Heading example

Do not:
```javascript
heading({ title: 'Hello, world' })
```

instead, [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) is the equivalent of setting the text for a DOM node.

Do:
```javascript
heading({ text: 'Hello, world' })
```

## Input example

Do not:
```javascript
input({ prefix: 'input-id', val: 'input-value' })
```

Do:
```javascript
input({ id: 'input-id', value: 'input-value' })
```

## Nested children example

If you are passing elements instead of text, yield or use 'children'

(parent/child is used to describe relationships between [nodes](https://developer.mozilla.org/en-US/docs/Web/API/Node)) 

Do not:
```javascript
fieldset({ inside: '<input type="text" />' })
```

Do: (yielding)
```javascript
fieldset() do
  <input type="text"/>
end
```

or
```javascript
fieldset({ children: '<input type="text" />' })
```

**Comment by nickcolley** [comment]
I could write this up clearer given more time if you wanted.

**Comment by nickcolley** [comment]
I'm closing out my old issues, if they're important we'll run into them again and action them.
