### ISSUE TITLE
Small checkbox filters have a gap in the hitbox

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_publishing_components#696]
Not sure if this is the right place to raise - let me know if not

Congrats on launching custom small checkboxes! Found a small issue - there's a small gap in the hit box between checkbox and label - might be nicer for the user without a gap. It might be better to have the whole option display block in this context - so you can click on the right if you like too.

![image](https://user-images.githubusercontent.com/1132904/50637360-a5cdb400-0f51-11e9-93bc-87d2f8ff5f5e.png)

**Comment by nickcolley** [comment]
Just FYI on the display block:

> have a margin to the right when the box is scrollable so that users can interact with a scrollbar without accidentally clicking an option

https://finder-frontend.herokuapp.com/component-guide/option-select Acceptance criteria.
