### ISSUE TITLE
govuk_frontend_toolkit variable references error in imported sass files

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_publishing_components#72]
govuk_frontend_toolkit variable references error in imported sass files when used in Static.

> Static didn't always load dependencies from govuk_frontend_toolkit when they were referenced from another file – putting them into a single file avoided the problem but the cause wasn't identified

See:
https://github.com/alphagov/govuk_publishing_components/pull/43
https://github.com/alphagov/govuk_publishing_components/commit/ab888f17e6ed6a3f031b2efe862e282b56b2c5ee

**Comment by nickcolley** [comment]
@fofr is this fixed now?

**Comment by fofr** [comment]
No, and given the way components share styles using imports it's probably broken again.

**Comment by alex-ju** [comment]
We're not using govuk_frontend_toolkit variables at this point, so I'm going to close this.
