### ISSUE TITLE
Possible injection if axe warning has HTML

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#736]
If you wrap the tag component's text with <marquee> it'll also apply to the axe warning since the output has HTML in the markup.

**Comment by nickcolley** [comment]
We could solve this by constructing this DOM with `document.createElement` and `textNode.textContent` which'll stop raw HTML from being rendered.

https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/component_guide/accessibility-test.js#L136

**Comment by barrucadu** [comment]
Here's a reproduction:

```
<%= tag.div class: "gem-c-tag" do %>
  <marquee><%= text %></marquee>
<% end %>
```

Maybe the most surprising lesson here is that Chrome still supports `<marquee>`.
