### ISSUE TITLE
Should hover appearance be an acceptance criteria?

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_publishing_components#84]
https://github.com/alphagov/govuk_publishing_components/blob/1b6fb0b5cde36f957945012a74a96a088467f912/app/models/govuk_publishing_components/shared_accessibility_criteria.rb#L12

I don't think appearance on hover should be an acceptance criteria.

If it did not change on hover, does that make it inaccessible? I don't think so. It may appear as acceptance criteria for the design of the component, but is not required for the component to be accessible.

**Comment by fofr** [comment]
This is specific to the accessibility of links within components.

**Comment by edwardhorsford** [comment]
@fofr Is hover is ever a requirement to make a link accessible?

**Comment by fofr** [comment]
This was a recommendation from @LJWatson that I agree with.

Changing appearance indicates when something is clickable at the current cursor position. If the appearance does not change the user may not know the link is clickable, or if they know it is clickable they may try to click on a more precise hit point than is necessary. This is an important consideration for users with reduced motor skills.

I’d also include a changing cursor in this definition. If a user hovered over a link and the cursor did not change I would consider that an accessibility failure.

**Comment by edwardhorsford** [comment]
It's not a major thing, but I still think it's being overly specific. It's a certainly a good thing to have (I'd want it in this component), but I disagree that it is inherently required to make links accessible.

I think the broader criteria it's trying to meet is that users should be clear they can click on it. This can be achieved in a number of ways - colour, underline, cursor, hover, etc. I believe accessibility acceptance criteria should try to avoid specifying the design solution and instead focus on what the user needs to understand.

**Comment by nickcolley** [comment]
I can see and agree with both sides, but since having this additional criteria isnt doing any harm that I can see I'll close this out.

Feel free to reopen if you think this is not the right decision.
