### ISSUE TITLE
Add install script to stub files needed by gem

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_publishing_components#91]
As a developer using the gem, it will be useful to have the setup automated.

Include a post-install script that stubs:
* Initialiser
* Added route
* Added component rake validation tasks to default task
* Maybe Heroku config?
* Maybe component directories

**Comment by nickcolley** [comment]
I'm going to close this one out since we raised it based on the initial gem work, if it's important we'll run into it again and action it.
