### ISSUE TITLE
Generic way to do nesting

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_publishing_components#97]
Passing children to a component could have some general principles

Ideas

- [React children](http://mxstbr.blog/2017/02/react-children-deepdive/)
- [ERB passing blocks](https://github.com/alphagov/collections/pull/394/files#r145348739)
- [Shadow DOM slots](https://developers.google.com/web/fundamentals/web-components/shadowdom#slots)

**Comment by tijmenb** [comment]
This gem uses the standard Rails way, so just calling `render 'components/my-component'` will work. Or do you mean something else?

**Comment by nickcolley** [comment]
I think this was solved when @steventux added block support.

**Comment by tijmenb** [comment]
👍
