### ISSUE TITLE
Email Signup Survey Broken

### ISSUE THREAD

**Issue by benthorner** [alphagov/govuk_publishing_components#997]
A [recent change](https://github.com/alphagov/govuk_publishing_components/pull/957) to the email signup survey has caused it to stop working, due to a missing hidden field (survey_source). After reading through the PR, I can't work out why this field was removed, as it doesn't seem to be related to the overall change and the value is still available to use.

<img width="681" alt="Screen Shot 2019-07-18 at 20 33 22" src="https://user-images.githubusercontent.com/9029009/61486710-0081a700-a99c-11e9-8fb6-ea33130437b1.png">

**Comment by andysellick** [comment]
@benthorner I'll take a look, this seems fairly urgent.
